// ─────────────────────────────────────────────────────────────────────────────
// SERVICE FAQ DATA - the verbatim question/answer pairs shown in each service
// page's "Frequently asked questions" section, used to generate the FAQPage
// JSON-LD (see serviceSchema.ts).
//
// AUTO-GENERATED from the rendered pages by scripts/gen-faqs.mjs. If a page's
// FAQ copy changes, rebuild and re-run that script so the schema stays in sync
// with what visitors actually see (Google requires the two to match).
// ─────────────────────────────────────────────────────────────────────────────

export const SERVICE_FAQS: Record<string, { q: string; a: string }[]> = {
  '/services/social-media-marketing': [
    { q: "How much do SMM services cost in Australia?", a: "Most Australian small businesses pay between $1,000 and $2,000 per month for professional organic social media management on one or two platforms, with content and monthly reporting included. A fuller program with more platforms, regular video, and a dedicated account manager usually runs $2,500 to $5,000 per month. Those figures cover management and content; if you add paid social ads, the ad spend goes to the platform separately and managing those ads adds a fee on top. The honest version is that price tracks content volume and platform count more than any fixed package, so we quote from what your business actually needs rather than a tier off a menu. Be wary of anything around $500 a month, which usually buys generic posts with no strategy behind them." },
    { q: "What is the role of an SMM company?", a: "An SMM company runs the social side of your marketing so you do not have to, and does it better than posting between meetings ever could. That covers the strategy (which platforms, what content, what you are trying to achieve), the content and design (posts, video, graphics), the day-to-day management (scheduling, publishing, and replying to comments and messages), and the reporting that tells you whether any of it is working. A good SMM company ties all of that to business outcomes, not follower counts. With EG Digital you also get branding, email, web, and paid ads under the same roof, so your social is joined up with everything else your marketing is doing instead of running as an island." },
  ],
  '/services/ppc-services': [
    { q: "What is the average cost of PPC services in Australia?", a: "Most Australian SMBs pay between $1,000 and $5,000 per month in management fees, charged either as a flat retainer or as roughly 10% to 20% of ad spend, with the percentage often falling as budgets grow. That fee is separate from the ad spend you pay the platforms, which for local businesses usually starts around $2,000 to $5,000 a month to produce steady lead flow. Competitive industries such as legal and finance run higher on both counts, because clicks cost more and the account needs more attention. The honest version is that price tracks your market and your platforms more than any fixed tier, so we quote from an audit of your actual account rather than a number off a menu." },
    { q: "How long does it take to see results from PPC?", a: "Faster than SEO, but not instant. Paid ads can drive clicks the day they go live, and many accounts see early leads within the first two to four weeks. The meaningful results, a stable cost per lead and a return on ad spend you can plan around, usually take two to three months, because the campaigns need data to learn from and we need real conversions to optimise against. A brand-new account with no history takes a little longer to settle than one we are improving. We would rather set that expectation honestly than promise overnight numbers we cannot hit." },
    { q: "Should I hire a freelancer or a PPC company?", a: "It depends on your budget and how much is riding on the outcome. A freelancer can be cheaper and works fine for a single, simple campaign, but you are relying on one person's availability and one skill set, and the landing page, tracking, and reporting often fall outside what they cover. A PPC company gives you a team: strategy, campaign management, copywriting, and the developers to fix the page and the tracking, with someone accountable when something breaks. With EG Digital you also get web, cloud, and software under the same roof, so the parts of a campaign that usually get handed off to a third party are handled in-house instead. For anything beyond a basic, low-stakes campaign, that integration is where the results come from." },
  ],
  '/services/web-development': [
    { q: "What is the average cost of web development in Australia?", a: "Most professional business websites in Australia fall between $5,000 and $15,000, with the sweet spot for many small businesses around $5,000 to $10,000. Fully custom builds run higher, and e-commerce or web-application projects with payments and integrations typically start near $15,000 and climb with complexity. The honest version is that price tracks functionality more than page count, so the right number depends on what your site has to do. We quote from your actual requirements and itemise it, rather than quoting a tier before we understand the project." },
    { q: "How long does it take to develop a professional website?", a: "For a straightforward custom business site, plan on roughly four to eight weeks from kickoff to launch. A simpler template-based build can be ready in two to four weeks, while a larger build with custom features, copywriting, and integrations runs closer to six to twelve weeks. Complex platforms and enterprise projects with multiple integrations can take longer again. The timeline depends on scope and on how quickly content and feedback come back from your side, which is why we agree on both before we begin." },
    { q: "Why should I choose a local Australian web company?", a: "A local team works in your timezone, understands the Australian market and its compliance expectations, and is straightforward to reach when something needs attention. Offshore developers can be cheaper, but the savings often come with communication overhead, quality uncertainty, and timezone gaps that slow everything down. With EG Digital you get an Australian team in Melbourne, accountable and reachable, plus engineers, hosting, and security in one place rather than scattered across providers and time zones." },
    { q: "Do Australian web companies offer SEO services?", a: "Many do, and the better ones build SEO into the development rather than treating it as an afterthought. We do both. Every site we build ships with the technical foundations search engines need: fast Core Web Vitals, clean structure, mobile-first rendering, and schema markup. EG Digital also runs full SEO and AI search optimisation as ongoing services, so the same team that builds your site can grow its traffic, instead of you having to brief a separate company on a site they did not build." },
    { q: "What technologies do top Australian companies use?", a: "It depends on the job, and a good company picks the tool that fits rather than forcing every project into the same stack. For content-driven business sites, WordPress and other established CMS platforms remain common because they are flexible and easy for your team to manage. For sites that need more speed and flexibility, headless CMS and modern JavaScript front-ends are increasingly the choice. For applications and complex logic, the build moves into custom development with proper databases, APIs, and cloud infrastructure. At EG Digital we match the technology to your needs and your team's ability to maintain it, and because we also handle software and cloud, we are not limited to one approach." },
  ],
  '/services/seo-services': [
    { q: "What is the difference between an SEO company and an SEO consultant?", a: "An SEO consultant is typically an individual who provides strategic advice, audits, or project-based guidance. An SEO company offers a broader team of specialists, including technical SEO experts, content strategists, link-building specialists, developers, and reporting analysts, to execute and scale an ongoing SEO program. At EG Digital, you get both strategic guidance and hands-on execution under one roof. Our strategists work alongside SEO specialists, content writers, and developers, ensuring recommendations are implemented quickly and aligned with your business goals. This integrated approach delivers faster execution, greater accountability, and better long-term results." },
    { q: "How long does SEO take to work in Australia?", a: "Most clients see measurable movement in three to six months, with stronger results across six to twelve. A brand-new site, or one with a weak technical foundation, takes longer because the groundwork has to be laid first. We would rather set that expectation honestly than promise a timeline we cannot hit." },
    { q: "Do I still need traditional SEO if AI search is taking over?", a: "Yes, and the reverse is also true. AI engines retrieve heavily from indexed web pages, so first-page Google rankings remain one of the strongest predictors of whether you get cited in an AI answer. Skipping SEO and going AI-only leaves the foundation those engines pull from unbuilt. We run both together for that reason." },
    { q: "What makes EG Digital a full-service SEO company?", a: "We cover the whole of search under one team: technical SEO, on-page and content, local SEO, off-page authority and digital PR, and AI search optimisation through AEO and GEO. Because EG Digital is also a web, cloud, and software partner, the technical work that usually waits in a developer queue gets handled in-house." },
    { q: "Will you lock me into a long contract?", a: "No. We work on flexible terms and earn the renewal by moving your numbers. A short minimum to let the work take effect is reasonable; a two-year lock-in is not, and we do not use them." },
    { q: "How do you measure SEO success?", a: "By outcomes that map to your business: organic enquiries and leads, the revenue they produce, rankings for commercial-intent keywords, your Search Console traffic trend, click-through rate, and, increasingly, your share of citations in AI answers. Rankings are in the report, but they are not the headline. Revenue is." },
    { q: "Which AI engines do you optimize for?", a: "ChatGPT, Perplexity, Claude, Google AI Overviews, Gemini, and Microsoft Copilot. Each retrieves and weights sources differently, so we tune the work per engine and track your citation share across all of them." },
    { q: "Do you provide SEO services outside Australia?", a: "Yes. While EG Digital is headquartered in Melbourne, we also deliver SEO campaigns for businesses targeting the UK, USA, Canada and Singapore. Every campaign is tailored to the search landscape, competitors and customer behaviour within the target country, ensuring your SEO strategy aligns with local search intent while maintaining a scalable international presence." },
  ],
  '/services/technical-seo': [
    { q: "What is technical SEO?", a: "Technical SEO is the practice of optimising the technical foundations of your website so search engines can crawl, index, render, and understand it, and so it loads fast and works well for users. It covers site speed and Core Web Vitals, crawlability and indexation, site architecture and internal linking, XML sitemaps, canonical tags and redirects, structured data and schema markup, mobile rendering, and security. It is separate from on-page content SEO and off-page link building, but it is the foundation both rely on: without a technically sound site, even great content and strong links struggle to rank. Fix the technical foundation and everything else you do works harder." },
    { q: "How often should you do a technical SEO audit?", a: "For most sites, a thorough technical SEO audit once or twice a year is sensible, with lighter ongoing monitoring in between so new issues get caught early rather than after they have cost you rankings. Larger, more complex, and frequently changing sites, big eCommerce stores especially, benefit from more frequent checks, because every new product, template change, or plugin can introduce a technical problem. You should also run a full audit before and after any major change: a site migration, a redesign, a platform switch, or a CMS upgrade. On a living site, technical SEO is an ongoing discipline rather than a one-time fix, which is why we build monitoring into our engagements." },
    { q: "Does technical SEO guarantee rankings?", a: "No, and any provider who guarantees a specific ranking is either misinforming you or about to waste your money, because no one controls Google's algorithm. What technical SEO does is remove the barriers stopping you from ranking: if search engines cannot crawl your pages, your site is too slow, or your architecture confuses them, you cannot rank no matter how good your content is. Fixing those foundations lets your content and links do their job, and it is often the highest-ROI SEO work available because one foundational fix can lift many pages at once. But rankings ultimately depend on the whole picture, technical health plus content quality plus authority, not technical SEO alone." },
    { q: "What is a crawl budget?", a: "Crawl budget is the number of pages a search engine will crawl on your site within a given timeframe, based roughly on how much it wants to crawl your site and how much your server can handle. For small sites it rarely matters, because search engines can easily crawl everything. For large sites, big eCommerce stores, news sites, and anything with thousands of URLs, it matters a lot: if crawl budget is wasted on low-value pages, duplicate URLs, endless faceted-navigation combinations, or broken links, your important pages may get crawled less often or missed entirely. Crawl budget optimization means directing that budget toward the pages that matter, by fixing duplicate content, tidying architecture, managing crawl directives, and cleaning up the URLs search engines should not be spending time on." },
  ],
  '/services/mobile-app-development-company-australia': [
    { q: "How much does it cost to develop an app in Australia?", a: "Most custom apps in Australia fall between $30,000 for a simple MVP and $150,000 for a mid-complexity build with payments, integrations, and a custom backend, while enterprise platforms commonly start around $200,000 and climb with complexity. Local developer rates generally sit around $150 to $200 an hour. The honest version is that price tracks functionality far more than screen count, so the right number depends on what your app has to do. We quote from your actual requirements and itemise it, and we will tell you where a cross-platform build could bring the cost down without hurting the result." },
    { q: "How long does it take to develop a mobile app?", a: "For a straightforward custom app, plan on roughly three to four months from kickoff to launch. A simple MVP can be ready sooner, while a larger build with multiple integrations, a custom backend, and enterprise requirements runs closer to six months or more. Timelines depend on scope and on how quickly feedback and content come back from your side, plus the App Store and Google Play review windows at the end, which is why we agree on scope and process before we begin rather than promising a date we cannot hold." },
    { q: "Which is the best app development company in Australia?", a: "\"Best\" depends on what you are building and what you need around it. The right partner for a simple consumer app is not always the right partner for a secure, integrated enterprise platform. What matters is engineering quality, transparency on price and timeline, ownership of your source code, and whether the team can handle the backend, security, and hosting rather than handing those off. With EG Digital you get an accountable Melbourne team plus software, cloud, and cyber security under one roof, which is exactly where app projects tend to succeed or fall over." },
    { q: "Do Australian app developers provide post-launch support?", a: "The good ones do, and it matters more than people expect. Operating systems update, devices change, and users expect fixes and new features, so an app without a support plan starts decaying the day it ships. We host, monitor, maintain, and secure the apps we build, and because the same team knows your product end to end, fixes and improvements do not sit in a stranger's queue. Ongoing maintenance typically runs 10 to 15 percent of the build cost per year, and we quote it up front." },
    { q: "Is it better to hire a local or offshore app developer?", a: "It depends on your budget and how much is riding on the outcome. Offshore developers can be cheaper per hour, but the savings often come with communication overhead, timezone gaps, quality uncertainty, and questions about who is accountable when something breaks or how your data is handled under Australian privacy law. A local team works in your timezone, understands the Australian market and its compliance expectations, and is straightforward to reach. With EG Digital you get an Australian team in Melbourne, accountable and reachable, plus engineers, hosting, and security in one place rather than scattered across providers and time zones." },
  ],
  '/services/local-seo': [
    { q: "How much does local SEO cost in Australia?", a: "For a single-location small business in a moderately competitive area, local SEO typically runs $1,000 to $2,500 per month, while businesses targeting a whole city or a competitive category usually sit in the $2,500 to $5,000 range. Google Business Profile management on its own often starts around $400 a month, and multi-location or highly competitive campaigns push beyond $5,000. The honest version is that price tracks your competition and the number of locations more than any fixed tier, so we quote from an audit of your actual situation. Be cautious of very cheap offshore \"local SEO,\" which usually means automated citation spam rather than a real strategy." },
    { q: "Does my Australian business need local SEO?", a: "If you serve customers in a specific area or have a physical location, then yes, almost certainly. Most people looking for a nearby business search Google or Google Maps first, and a large share of those searches lead to a call or visit within a day. If you are not showing up in the map pack and local results for your area, those customers are finding a competitor instead. The businesses that benefit most are the ones with a service area or a shopfront: trades, clinics, professional services, hospitality, and retail. A purely national online business with no local footprint is the main exception, and even then location signals can still help." },
    { q: "How do I rank higher on Google Maps in Australia?", a: "Ranking in the Google Maps three-pack comes down to a few things working together: a complete, well-optimised Google Business Profile with the right categories and services, consistent business details across directories, a steady stream of genuine reviews, proximity to the searcher, and local signals from your website like location pages and LocalBusiness schema. There is no single switch, and there is no legitimate shortcut. It is the sum of those signals maintained over time, which is exactly what a proper Google Maps ranking service manages on your behalf. Anyone promising instant top-three placement is overselling." },
    { q: "What is the difference between SEO and local SEO?", a: "Regular SEO is about ranking your website for relevant searches generally, wherever the searcher is. Local SEO adds a geographic focus: it optimises for location-based searches and for the Google Maps results, so you show up when someone nearby searches for what you offer, including \"near me\" queries. Local SEO uses the same technical and on-page foundations as regular SEO, but layers on the pieces that standard SEO does not touch, chiefly your Google Business Profile, local citations, reviews, and location-specific content. On the strategy question of local versus national SEO, the simple version is that local wins you a defined area faster and more affordably, while national SEO chases a broader market that takes longer and costs more, and most local businesses are far better served starting local." },
  ],
  '/services/off-page-seo': [
    { q: "What is included in off-page SEO services?", a: "Off-page SEO services cover everything done outside your website to build its authority: earning high-quality backlinks through outreach and digital PR, guest posting on relevant sites, building brand mentions and citations, analysing your backlink profile, researching competitor links, and disavowing toxic ones. At EG Digital it also includes monthly reporting tied to leads and rankings, so you can see what the authority work actually produced." },
    { q: "Are off-page SEO services worth the investment?", a: "Yes, for almost any business competing in search. Backlinks and authority remain among Google's strongest ranking signals, and they increasingly decide whether AI engines cite your brand too. The catch is that quality matters far more than quantity: a few links from trusted, relevant sites outperform hundreds of cheap ones, which can actively harm you. Done properly with white-hat methods, off-page SEO compounds over time and keeps paying off long after the work is done." },
    { q: "What is the best off-page SEO company for a small business in Australia?", a: "The best off-page SEO company for a small business is one that builds links the white-hat way, reports on leads rather than vanity metrics, and does not lock you into a long contract. Avoid anyone selling cheap bulk backlinks, which risk a Google penalty. EG Digital builds focused, affordable off-page campaigns for Australian small businesses, starting where your money works hardest and scaling as the results prove out." },
    { q: "How can I improve off-page SEO for a local Australian business?", a: "Start by earning links and mentions from local and industry-relevant sources: local publications, industry associations, and complementary businesses in your area. Consistent citations, genuine reviews, and coverage on trusted regional sites all build the local authority Google rewards. Combine that with a clean backlink profile, remove any toxic links, and pair it with strong local SEO so the authority you earn translates into rankings and enquiries in your area." },
    { q: "What impact do social signals have on off-page SEO rankings?", a: "Social signals like shares, mentions, and engagement are not a direct Google ranking factor, but they support off-page SEO indirectly. Content that spreads on social gets seen by more people, which increases the chance of earning genuine backlinks and brand mentions, the signals that do move rankings. Social activity also builds the brand recognition that AI engines increasingly read as a marker of authority, so it is worth doing as part of the wider picture." },
    { q: "How is off-page SEO different from on-page SEO?", a: "On-page SEO covers what you control on your own site: content, keywords, structure, and technical health. Off-page SEO covers what happens off your site: backlinks, brand mentions, and the authority signals that tell Google your business is credible and worth ranking. On-page lays the groundwork and off-page builds the reputation, and you need both working together to reach and hold the top of search. EG Digital runs both under one team for that reason." },
  ],
  '/services/facebook-ads-management': [
    { q: "What is the average cost of FB ads service in Australia?", a: "There are two costs and they are different. The first is ad spend, which is what you pay Meta to show your ads. In Australia the average cost per click sits around $1.50 for 2026, typically ranging from about $0.50 to $2.00, with cost per thousand impressions somewhere around $10 to $15 and much higher in competitive categories such as finance and legal. The second is the management fee, which is what you pay an agency to run the account. That typically runs $1,000 to $5,000 a month, charged as a flat retainer or as roughly 15% to 20% of ad spend, with the percentage often falling as budgets grow. Creative production is sometimes scoped on top. The honest version is that price tracks your industry, your creative, and your objective more than any fixed tier, so we quote from an audit of your actual account rather than a number off a menu." },
    { q: "Can I get a free Facebook ads consultation in Australia?", a: "Yes. We offer a free, no-obligation Facebook ads consultation and audit to any Australian business. We review your existing account, or your market if you are starting fresh, look at what your competitors are running, and give you a straight read on where your budget is leaking and what it should be bringing back. You get the findings whether or not you go on to work with us, and there is no lock-in attached to it." },
    { q: "How do Facebook interest targeting tools work?", a: "Meta builds a profile of what each user is interested in, based on the pages they follow, the content they engage with, and the products and activities they interact with across Facebook and Instagram. Interest targeting lets you reach people by those signals, so a camping brand can target people interested in hiking and the outdoors, for example. In practice, interest audiences are one lever among several. We test them against custom audiences built from your own data and lookalike audiences that mirror your best customers, then keep whichever combination actually converts. Broad interest targeting can waste budget on cheap, low-intent clicks, so the skill is in building the audience deliberately and reading the results, not just ticking interest boxes." },
    { q: "Is hiring a Facebook ads expert worth it?", a: "For anything beyond boosting the occasional post, yes, and the maths usually makes the case. A self-managed account typically wastes a real share of its budget on the wrong audiences and worn-out creative, and it rarely has the tracking set up properly, which means it cannot optimise against real results. An expert brings the audience strategy, the creative testing, the correct pixel and Conversions API setup, and the ongoing optimisation that brings your cost per result down. With EG Digital you also get designers, copywriters, and the developers to fix the landing page and tracking under the same roof, so the parts of a campaign that usually get handed off to a third party are handled in-house. The management fee is only worth it if it recovers more than it costs, which is exactly the bar we hold ourselves to." },
    { q: "What are the best practices for Facebook ads in Australia?", a: "The fundamentals hold across markets, but a few matter most. Get the tracking right first: the Meta Pixel and the Conversions API, so your campaigns can see real conversions since Apple's privacy changes. Lead with creative, because it is the biggest driver of performance and it fatigues fast, so refresh it on a schedule. Build audiences from your own first-party data where you can, then extend with lookalikes and interest targeting, rather than relying on broad targeting alone. Fund the testing phase properly, because underfunding it is the most common reason campaigns fail. And measure against cost per result and return on ad spend, not likes and reach. Beyond that, Australian budgets should account for seasonal cost spikes, especially the Q4 run-up to Christmas when competition drives prices up." },
    { q: "Do you run Instagram ads as well as Facebook?", a: "Yes, and usually in the same campaign. Facebook and Instagram both run through Meta Ads Manager, so a single campaign can reach your audience across both platforms, plus placements like Reels and Stories. We choose the placement mix based on where your audience is and where your creative performs, rather than splitting your budget into two disconnected efforts." },
  ],
  '/services/google-ads-management': [
    { q: "How much do Google Ads cost in Australia?", a: "There are two costs and they are different. The first is ad spend, which is what you pay Google for the clicks. In Australia that averages roughly $2 to $4 per click for search, rising well past $10 in competitive categories such as legal and finance, and most SMBs budget between $1,500 and $5,000 a month to produce steady lead flow. The second is the management fee, which is what you pay an agency to run the account. That typically runs $1,000 to $5,000 a month, charged as a flat retainer or as roughly 10% to 20% of ad spend, with the percentage often falling as budgets grow. A one-off setup fee is common on top. The honest version is that price tracks your industry and your competition more than any fixed tier, so we quote from an audit of your actual account rather than a number off a menu." },
    { q: "Are Google Ads worth it for small businesses?", a: "Yes, when the account is targeted and managed properly, and no when it is left on autopilot. Google Ads puts you in front of people at the exact moment they are searching for what you sell, which is why it converts better than most channels, and you control the budget down to the day. The catch is that a loose account wastes a real share of its spend on searches that it will never buy, which is where the reputation for \"Google Ads not working\" usually comes from. For a small business, the smart approach is to start with a focused budget on your highest-intent keywords, prove it pays, then scale, rather than spreading thin across every campaign type at once. Done that way, it is one of the fastest ways to generate enquiries a small business has." },
    { q: "How long does it take to see results from Google Ads?", a: "Faster than SEO, but not instant. Google Ads can drive clicks the day the campaign goes live, and many accounts see early leads within the first two to four weeks. The meaningful results, a stable cost per lead and a return on ad spend you can plan around, usually take two to three months, because the campaigns need data to learn from and we need real conversions to optimise against. A brand-new account with no history takes a little longer to settle than one we are improving. We would rather set that expectation honestly than promise overnight numbers we cannot hit." },
    { q: "Should I hire a freelancer or a Google Ads agency?", a: "It depends on your budget and how much is riding on the outcome. A freelancer can be cheaper and works fine for a single, simple campaign, but you are relying on one person's availability and one skill set, and the landing page, tracking, and reporting often fall outside what they cover. A Google Ads agency gives you a team: strategy, campaign management, copywriting, and the developers to fix the page and the tracking, with someone accountable when something breaks. With EG Digital you also get web, cloud, and software under the same roof, so the parts of a campaign that usually get handed off to a third party are handled in-house. For anything beyond a basic, low-stakes campaign, that integration is where the results come from." },
    { q: "Do you take a percentage of my ad spend?", a: "Only if that is the model that suits your account, and never as a hidden markup. You can be billed a flat monthly retainer or a percentage of spend, whichever fits, and either way 100% of your ad budget goes to Google. We spell the fee out in a scope document before you commit, and we do not use uncapped percentage models that reward us for spending more of your money regardless of whether it works." },
    { q: "Can you audit and take over an existing Google Ads account?", a: "Yes, and it is one of the most common ways clients start with us. We audit your current account, show you where it is leaking and what is worth keeping, then rebuild what needs rebuilding and leave the rest. You keep ownership of your account and your history throughout. You get the audit findings whether or not you go on to work with us." },
  ],
  '/services/linkedin-ads-management': [
    { q: "Is LinkedIn advertising effective for Australian businesses?", a: "Yes, for the right kind of business. LinkedIn is the most effective channel in Australia for reaching decision-makers by job title, seniority, industry, and company size, which is why B2B advertisers consistently rate its leads as their highest quality. It works best for businesses with a considered, higher-value sale, longer sales cycles, and buying decisions that involve several stakeholders, because LinkedIn keeps you visible and credible throughout that process. It is less suited to low-value or impulse purchases, where the cost per click is hard to justify. The honest test is your deal value and your sales cycle: if one client is worth thousands and the decision takes weeks, LinkedIn usually pays. If not, we will point you somewhere cheaper." },
    { q: "How much should I spend on LinkedIn ads?", a: "Enough to gather real data, and no more than your economics justify. LinkedIn's technical minimum is a $10 daily budget, but the practical floor for a B2B campaign is closer to $50 to $100 a day, because below that you generate clicks too slowly to learn anything. In Australian terms, most meaningful programs start at $1,500 to $5,000 a month in ad spend, separate from management fees, with competitive industries and senior audiences needing more. The right number works backwards from your goal: if you know your cost per lead, your lead-to-client rate, and how many clients you need, you can size the budget to hit it. We run that maths against your actual numbers rather than quoting a figure off a menu." },
    { q: "Can I hire someone to manage my LinkedIn ads?", a: "Yes, and on a platform this expensive it usually pays for itself. LinkedIn punishes poorly built accounts with even higher costs, so the difference between a specialist and a self-managed campaign shows up directly in your cost per lead. A good manager brings the audience strategy, the right format choices, the creative testing, the correct tracking, and the CRM connection that gets leads to your sales team, plus the ongoing optimisation that keeps a premium budget from leaking. With EG Digital you also get designers, copywriters, and the developers to fix the landing page and CRM under the same roof, so the parts of a B2B campaign that usually get handed off to a third party are handled in-house. The management fee is only worth it if it recovers more than it costs, which is the bar we hold ourselves to." },
    { q: "How do you set up LinkedIn ads for a new client?", a: "We start with a fit check, because there is no point setting up a channel that will not pay. Assuming LinkedIn suits the business, we define the objective and the target audience by role, seniority, industry, and company size, then get the tracking right: the LinkedIn Insight Tag, conversion tracking, and the CRM connection so leads reach the sales team. From there we build the campaign structure, choose the ad formats that match the objective, design the creative, and write the copy, then launch with a budget structured across the funnel. Once live, we optimise continuously against cost per lead and cost per opportunity, and report back in plain language. You see the reasoning at every step." },
    { q: "How can I improve my LinkedIn ad conversion rates?", a: "The biggest levers are targeting, format, and the offer. Tighten the audience so your spend only reaches genuine decision-makers, then use LinkedIn's Lead Gen Forms, which pre-fill from the user's profile and consistently convert better than sending people to a landing page because there is less friction. Make sure the offer is worth a considered buyer's attention, a webinar, a piece of original research, a genuinely useful resource, rather than a generic \"contact us.\" Refresh creative before it fatigues, since LinkedIn's audiences are smaller and see your ads sooner. And connect everything to your CRM so you can see which audiences and messages actually produce opportunities, then shift budget toward them. Conversion rate on LinkedIn is won in the setup, not the bid." },
  ],
  '/services/branding': [
    { q: "What is included in a branding package?", a: "It depends on the scope, but a proper branding package covers more than a logo. At a minimum it includes brand strategy (your positioning, values, and audience), a visual identity (logo, colour palette, typography, and imagery style), and a set of brand guidelines that document how it all should be used. A fuller package adds brand messaging and voice, a broader identity system with templates and assets, and rollout across your channels. Cheap \"branding packages\" are often just a logo and a colour swatch with no strategy behind them, which is why they rarely change anything. With EG Digital you get the strategy, the identity, the messaging, the guidelines, and the source files, so the brand is complete and yours to use." },
    { q: "How long does the branding process take?", a: "Most branding projects take somewhere between four and twelve weeks, depending on scope and how much research and strategy is involved. A focused identity project for a small business can move faster; a full strategy-led brand or a rebrand for an established company takes longer because the groundwork, research, positioning, and stakeholder input, has to be done properly first. We would rather set that expectation honestly than rush the strategy and hand you a brand that looks fine but does not fit. You will get a clear timeline up front, mapped to the scope we agree on." },
    { q: "What is the difference between branding and a logo?", a: "A logo is one small part of a brand. The logo is a mark that identifies you; the brand is everything people think, feel, and expect when they see it, which includes your positioning, your messaging, your voice, your visual identity, and every experience someone has with your business. A logo without a brand behind it is just a picture. A strong brand makes the logo mean something. We build the whole brand, strategy and identity together, so your logo is the visible tip of something with substance underneath it, not the entire exercise." },
    { q: "Do you provide the brand files and guidelines?", a: "Yes, as standard. You get the source files for your identity, the editable originals rather than flat images you cannot change, along with a set of brand guidelines that document how your brand should be used. That means you, and any designer or agency you work with later, can apply and extend the brand without rebuilding it from scratch. Some providers hold files back or charge to release them, which locks you in. We hand everything over, because the brand is yours." },
  ],
  '/services/email-marketing': [
    { q: "How much do email marketing services cost in Australia?", a: "Most Australian small businesses pay between $500 and $1,500 per month for an ongoing email program with a regular campaign or newsletter, a couple of core automations, and monthly reporting. A fuller program with frequent campaigns, a full suite of automated flows, custom design, and detailed reporting usually runs $1,500 to $4,000 per month, and one-off projects like a template build or an automation setup are scoped separately. Your email platform, such as Klaviyo or Mailchimp, is billed by the provider on top and usually scales with your list size. The honest version is that price tracks how much you send and how much is custom rather than any fixed package, so we quote from what your business actually needs. Be wary of very cheap packages, which usually mean a generic template blasted to your whole list with no strategy behind it." },
    { q: "Are email marketing services worth it for startups?", a: "For most startups, yes, and often sooner than they expect. Email is one of the cheapest channels you have, and unlike ads, it keeps working after you stop paying: a welcome sequence set up once nurtures every new subscriber for months, and a list you own is not at the mercy of an algorithm or a rising ad cost. The catch is that email rewards doing it properly, since a generic blast to a tiny list does little. The value comes from the right automation and segmentation, which is where a service earns its fee. For an early-stage startup we usually start small, a welcome flow and a regular campaign, prove the return, then build from there rather than committing to a large program before the list is big enough to justify it." },
  ],
}
